### ISSUE TITLE
Number of cat form is wrong in 3.3.5 Onyxia TBC version

### ISSUE THREAD

**Issue by snowu** [Carnivohra/NugEnergy3.3.5a#1]
https://github.com/Carnivohra/NugEnergy3.3.5a/blob/f1c3a990d0e06277eeb33572761c05d125c240de/NugEnergy/NugEnergy.lua#L181

Currently energy ticket is shown only in travel form on Onyxia, changing
to
`            local , , catactive,  = GetShapeshiftFormInfo(2)
`
fixes it

**Comment by Carnivohra** [comment]
ty :) fixed

**Comment by snowu** [comment]
I am dumb, sorry! It was due to me not having the acquatic form yet (at 70, yes :D) and assuming the form numbers were fixed but they are not. Reverting to before works as expected

I did more changes to allow energy ticker to be shown in every form, which is neat for me but not sure you want to implement it for anyone. Lmk and I can push changes
